title: QMK Configurator
email: hackneyed@gmail.com
show_downloads: true
description: QMK for potatoes - an open source configurator for QMK Firmware (only the AVR boards right now)
baseurl: "/qmk_configurator"
url: "http://hackneyed.github.io"
github_username: hackneyed
repository: hackneyed/qmk_configurator
theme: jekyll-theme-minimal
